name: Build documentation

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
    - name: Build documentation
      run: |
        python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs docs/_build/html -n -W
    - uses: actions/upload-artifact@v2
      name: Upload docs as artifact
      with:
        name: docs-html
        path: './docs/_build/html'
        if-no-files-found: error
